/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import vistas.Devoluciones;
import vistas.Libros;
import vistas.Prestamos;
import vistas.Reportes;
import vistas.Usuarios;

/**
 *
 * @author NelsonRO
 */
public class Inicio extends javax.swing.JFrame {

    
    private ImageIcon icono;
    private ImageIcon imagen;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        
        this.setLocationRelativeTo(this);
        this.imagenbiblioteca(lblimagen1, "src/Imagenes/biblioteca.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnusuarios = new javax.swing.JButton();
        btnprestamos = new javax.swing.JButton();
        btnlibros = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btndevoluciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblimagen1 = new javax.swing.JLabel();
        btnreportes = new javax.swing.JButton();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1084, 612));
        setResizable(false);
        setSize(new java.awt.Dimension(1084, 612));

        jPanel2.setBackground(new java.awt.Color(102, 0, 50));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(178, 148));

        btnusuarios.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnusuarios.setText("Usuarios");
        btnusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuariosActionPerformed(evt);
            }
        });

        btnprestamos.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnprestamos.setText("Prestamos");
        btnprestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprestamosActionPerformed(evt);
            }
        });

        btnlibros.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnlibros.setText("Libros");
        btnlibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlibrosActionPerformed(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btndevoluciones.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btndevoluciones.setText("Devoluciones");
        btndevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndevolucionesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Biblioteca");

        lblimagen1.setName(""); // NOI18N

        btnreportes.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnreportes.setText("Reportes");
        btnreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(btnprestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndevoluciones, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(btnusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnreportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblimagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(btnprestamos)
                .addGap(18, 18, 18)
                .addComponent(btndevoluciones)
                .addGap(18, 18, 18)
                .addComponent(btnusuarios)
                .addGap(18, 18, 18)
                .addComponent(btnlibros)
                .addGap(18, 18, 18)
                .addComponent(btnreportes)
                .addGap(18, 18, 18)
                .addComponent(btnsalir)
                .addGap(26, 26, 26)
                .addComponent(lblimagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuariosActionPerformed
        Usuarios pl=new Usuarios();
        pl.setSize(900,600);
        pl.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(pl, 0);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_btnusuariosActionPerformed

    private void btnprestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprestamosActionPerformed
        
        Prestamos pl=new Prestamos();
        pl.setSize(900,600);
        pl.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(pl, 0);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_btnprestamosActionPerformed

    private void btnlibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlibrosActionPerformed
        Libros pl=new Libros();
        pl.setSize(900,600);
        pl.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(pl, 0);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_btnlibrosActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "¿Desea cerrar la aplicación?", "Cerrar aplicación", JOptionPane.YES_NO_OPTION);
        
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btndevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndevolucionesActionPerformed
        Devoluciones pl=new Devoluciones();
        pl.setSize(900,600);
        pl.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(pl, 0);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_btndevolucionesActionPerformed

    private void btnreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportesActionPerformed
        Reportes pl=new Reportes();
        pl.setSize(900,600);
        pl.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(pl, 0);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_btnreportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
//imagen del inicio
    public void imagenbiblioteca (JLabel lblimagen1, String ruta){
         this.imagen = new ImageIcon(ruta);
         this.icono = new ImageIcon(
    this.imagen.getImage().getScaledInstance(lblimagen1.getWidth(), lblimagen1.getHeight(), java.awt.Image.SCALE_DEFAULT)
    );
    lblimagen1.setIcon(this.icono);
    this.repaint();
}
    
    //traer un panel
    public static void mostrarjpanel(JPanel p) {
        p.setSize(900,600);
        p.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(p, 0);
        contenido.revalidate();
        contenido.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndevoluciones;
    private javax.swing.JButton btnlibros;
    private javax.swing.JButton btnprestamos;
    private javax.swing.JButton btnreportes;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnusuarios;
    private static javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblimagen1;
    // End of variables declaration//GEN-END:variables
}
